### PR TITLE
User Options

### PR DESCRIPTION
**Pull request by bitttttten**
Released under "2.2.0-beta".

### CODE REVIEW

**Comment by ccesare** [comment]
Works great! The only issue I'm seeing is that the installed version of `2.2.0-beta` has a couple `console.log`s that produce output when testing. They aren't on this branch, but they show up in the `index.js` file in `node_modules/jest-transformer-mdx` locally.

**Comment by bitttttten** [comment]
Oof yeah, I forgot to stash my changes before releasing 🤦

**Comment by bitttttten** [comment]
Released without the logs under "2.2.0-beta.1" :, )

**Comment by bitttttten** [comment]
Also I just finished upgrading some projects to 2.2.0-beta.1, no logs 🎉  and no issues 👍

**Comment by ccesare** [comment]
Working great for me!

**Comment by bitttttten** [comment]
Upgraded another project and also didn't hit any regressions. Nice!

Released under 2.2.0 🎉 

Thanks again :3

**Comment by ccesare** [comment]
Awesome. Thank you!

**Pull request merged**
